# Generated by Django 5.1.1 on 2025-02-06 06:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('personal_id', models.CharField(blank=True, max_length=45, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='laboratory',
            fields=[
                ('laboratory_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('department', models.CharField(blank=True, max_length=45, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modules', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='item_inventory',
            fields=[
                ('inventory_item_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('qty', models.IntegerField()),
                ('optimal_temperature', models.FloatField(blank=True, null=True)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('inventory', 'Inventory Management'), ('borrowing', 'Borrowing'), ('clearance', 'Clearance'), ('reservation', 'Laboratory Reservation'), ('reports', 'Reports')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='borrow_info',
            fields=[
                ('borrow_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('b_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('questions_responses', models.JSONField(blank=True, default=dict)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_by', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='borrowing_config',
            fields=[
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.laboratory')),
                ('allow_walkin', models.BooleanField(default=False)),
                ('allow_prebook', models.BooleanField(default=False)),
                ('prebook_lead_time', models.IntegerField(default=0)),
                ('allow_shortterm', models.BooleanField(default=True)),
                ('allow_longterm', models.BooleanField(default=True)),
                ('questions_config', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='item_description',
            fields=[
                ('item_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(blank=True, max_length=45, null=True)),
                ('alert_qty', models.IntegerField(blank=True, null=True)),
                ('add_cols', models.CharField(blank=True, max_length=255, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('rec_per_inv', models.BooleanField(default=False)),
                ('allow_borrow', models.BooleanField(default=False)),
                ('is_consumable', models.BooleanField(default=False)),
                ('rec_expiration', models.BooleanField(default=False)),
                ('expiry_type', models.CharField(blank=True, choices=[('Date', 'Date'), ('Usage', 'Usage'), ('Maintenance', 'Maintenance'), ('Temperature', 'Temperature')], max_length=45, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('maintenance_interval', models.IntegerField(blank=True, null=True)),
                ('qty_limit', models.IntegerField(blank=True, null=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='item_expirations',
            fields=[
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.item_inventory')),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('remaining_uses', models.IntegerField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_description'),
        ),
        migrations.CreateModel(
            name='item_handling',
            fields=[
                ('item_handling_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('changes', models.CharField(max_length=1)),
                ('qty', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item_inventory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='item_types',
            fields=[
                ('itemType_id', models.AutoField(primary_key=True, serialize=False)),
                ('itemType_name', models.CharField(blank=True, max_length=45, null=True)),
                ('add_cols', models.TextField(default='[]')),
                ('is_consumable', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='item_description',
            name='itemType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item_types'),
        ),
        migrations.CreateModel(
            name='laboratory_roles',
            fields=[
                ('roles_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='laboratory_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(default='A', max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.laboratory_roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('module', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.module')),
            ],
        ),
        migrations.CreateModel(
            name='reported_items',
            fields=[
                ('report_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('qty_reported', models.IntegerField()),
                ('report_reason', models.CharField(max_length=255)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (0, 'Cleared')], default=1)),
                ('borrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.borrow_info')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_description')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reservation_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('class', 'Class Time'), ('hourly', 'Hourly')], default='class', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('require_payment', models.BooleanField(default=False)),
                ('approval_form', models.FileField(blank=True, null=True, upload_to='approval_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('tc_description', models.TextField(blank=True, null=True)),
                ('leadtime', models.PositiveIntegerField(default=0)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_reservable', models.BooleanField(default=True)),
                ('blocked_time', models.CharField(default='{}', max_length=45)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=45, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('blocked_time', models.JSONField(default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='laboratory_reservations',
            fields=[
                ('reservation_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='P', max_length=1)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('num_people', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('filled_approval_form', models.FileField(blank=True, null=True, upload_to='filled_approval_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.rooms')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.roomtable')),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('suppliers_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=45)),
                ('contact_person', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliers'),
        ),
        migrations.CreateModel(
            name='borrowed_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('returned_qty', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=1, null=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.borrow_info')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_description')),
            ],
            options={
                'unique_together': {('borrow', 'item')},
            },
        ),
        migrations.CreateModel(
            name='laboratory_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory_roles')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissions')),
            ],
            options={
                'unique_together': {('role', 'laboratory', 'permissions')},
            },
        ),
    ]
