# Generated by Django 5.1.1 on 2025-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprogress',
            name='wip_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/wip_images/'),
        ),
    ]
