# Generated by Django 5.1.1 on 2024-09-23 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_types',
            fields=[
                ('itemType_id', models.AutoField(primary_key=True, serialize=False)),
                ('laboratory_id', models.CharField(blank=True, max_length=45, null=True)),
                ('itemType_name', models.CharField(blank=True, max_length=45, null=True)),
                ('add_cols', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('suppliers_id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_description',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(blank=True, max_length=45, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=10, null=True)),
                ('add_cols', models.CharField(blank=True, max_length=45, null=True)),
                ('alert_Qty', models.CharField(blank=True, max_length=45, null=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('itemType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item_types')),
            ],
        ),
        migrations.CreateModel(
            name='item_inventory',
            fields=[
                ('inventory_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_purchased', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('purchase_price', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_description')),
            ],
        ),
        migrations.CreateModel(
            name='item_handling',
            fields=[
                ('item_handling_id', models.AutoField(primary_key=True, serialize=False)),
                ('updatedon', models.DateTimeField(blank=True, null=True)),
                ('changes', models.CharField(blank=True, max_length=1, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=45, null=True)),
                ('updatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item_inventory')),
            ],
        ),
        migrations.CreateModel(
            name='item_transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.item_transactions'),
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliers'),
        ),
    ]
