# Generated by Django 4.2.16 on 2024-09-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='modules',
            field=models.ManyToManyField(to='core.Module'),
        ),
    ]
