# Generated by Django 5.1.1 on 2024-09-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='end_username',
        ),
        migrations.RemoveField(
            model_name='item_expirations',
            name='end_username',
        ),
        migrations.RemoveField(
            model_name='item_expirations',
            name='end_userreason',
        ),
        migrations.RemoveField(
            model_name='item_inventory',
            name='end_username',
        ),
        migrations.RemoveField(
            model_name='item_inventory',
            name='end_userreason',
        ),
        migrations.RemoveField(
            model_name='item_types',
            name='end_username',
        ),
        migrations.RemoveField(
            model_name='item_types',
            name='end_userreason',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='end_username',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='end_userreason',
        ),
    ]
