# Generated by Django 5.1.1 on 2024-09-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_item_description_end_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_description',
            old_name='disabled',
            new_name='is_disabled',
        ),
        migrations.AddField(
            model_name='item_description',
            name='rec_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
