# Generated by Django 5.1.1 on 2025-02-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='b_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
