# Generated by Django 4.2.16 on 2024-09-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_laboratory_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='modules',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='modules',
            field=models.ManyToManyField(to='core.module'),
        ),
    ]
