# Generated by Django 5.1.1 on 2024-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_types_suppliers_item_description_item_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_inventory',
            name='amount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='qty',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
