# Generated by Django 5.1.1 on 2025-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workinprogress_wip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_description',
            name='lead_time_prep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinprogress',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Cleared')], default='A', max_length=1),
        ),
    ]
