# Generated by Django 5.1.1 on 2024-10-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_laboratory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorymodule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
