# Generated by Django 5.1.1 on 2024-09-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_inventory_amount_item_inventory_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_description',
            old_name='alert_Qty',
            new_name='qty',
        ),
    ]
