# Generated by Django 5.1.1 on 2025-02-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_borrow_info_b_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_items',
            name='inventory_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
