# Generated by Django 5.1.1 on 2024-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_disabled_item_description_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_handling',
            name='updated_on',
            field=models.DateTimeField(default='9999-99-99 99:99'),
        ),
    ]
