# Generated by Django 5.1.1 on 2025-02-26 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_description_lead_time_prep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_items',
            name='cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearance_cleared_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
