# Generated by Django 5.1.1 on 2024-09-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_disabled_item_description_is_disabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_handling',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='item_handling',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='item_handling',
            name='action',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='item_handling',
            name='updatedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='item_handling',
            name='updatedon',
            field=models.DateTimeField(default='9999-99-99 99:99'),
        ),
        migrations.AddField(
            model_name='item_types',
            name='fixed_choices',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='item_types',
            name='add_cols',
            field=models.TextField(default='[]'),
        ),
    ]
