# Generated by Django 5.1.1 on 2024-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_disabled_item_description_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_handling',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_types',
            name='add_cols',
            field=models.TextField(default='[]'),
        ),
    ]
