# Generated by Django 5.1.1 on 2025-02-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_borrowed_items_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='is_wip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrow_info',
            name='wip_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow_info',
            name='wip_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrow_info',
            name='wip_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
