# Generated by Django 5.1.1 on 2024-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_role_rename_role_laboratory_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboratory_users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
