# Generated by Django 5.1.1 on 2024-09-30 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_handling_updated_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow_info',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('borrow_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
