# Generated by Django 5.1.1 on 2024-09-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_handling_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item_description',
            name='dimension',
        ),
    ]
