# Generated by Django 5.1.1 on 2024-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_alert_qty_item_description_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_transactions',
            name='remarks',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
