# Generated by Django 5.1.1 on 2024-09-28 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_item_handling_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_handling',
            name='updatedon',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
