# Generated by Django 5.1.1 on 2025-02-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_borrow_info_is_wip_borrow_info_wip_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_info',
            name='is_wip',
        ),
        migrations.RemoveField(
            model_name='borrow_info',
            name='wip_end_time',
        ),
        migrations.RemoveField(
            model_name='borrow_info',
            name='wip_notes',
        ),
        migrations.RemoveField(
            model_name='borrow_info',
            name='wip_start_time',
        ),
    ]
