# Generated by Django 5.1.1 on 2024-09-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_transactions_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_inventory',
            name='amount',
        ),
        migrations.AlterField(
            model_name='item_description',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
