# Generated by Django 5.1.1 on 2024-09-30 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_borrow_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowed_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.borrow_info')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_description')),
            ],
            options={
                'unique_together': {('borrow', 'item')},
            },
        ),
    ]
