# Generated by Django 5.1.1 on 2025-02-27 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shoppingitem_added_by_shoppingitem_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='existing_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_description'),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='added_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
