# Generated by Django 5.1.1 on 2024-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_handling_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_handling',
            name='updatedon',
            field=models.DateTimeField(default='9999-12-31 23:59'),
        ),
    ]
