# Generated by Django 5.1.1 on 2025-02-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shoppingitem_existing_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
