# Generated by Django 5.1.1 on 2025-02-06 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_borrow_info_is_wip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInProgress',
            fields=[
                ('wip_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(help_text='Describe the experiment and items left in the lab.')),
                ('status', models.CharField(choices=[('A', 'Active'), ('C', 'Completed')], default='A', max_length=1)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks.', null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wip_experiments', to='core.laboratory')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_experiments', to='core.roomtable')),
            ],
        ),
    ]
