# Generated by Django 5.1.1 on 2024-09-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_item_handling_updatedon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_handling',
            name='updatedon',
        ),
    ]
