# Generated by Django 5.1.1 on 2024-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_item_inventory_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='alert_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
