# Generated by Django 5.1.1 on 2024-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_id_number_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
