# Generated by Django 5.1.1 on 2025-02-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workinprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workinprogress',
            name='table',
        ),
    ]
