# Generated by Django 5.1.1 on 2025-03-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shoppingitem_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_inventory',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='inventory_pdfs/'),
        ),
    ]
