# Generated by Django 5.1.1 on 2024-09-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_description_alert_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
