# Generated by Django 5.1.1 on 2025-02-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_workinprogress_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinprogress',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wip_experiments', to='core.rooms'),
        ),
    ]
