# Generated by Django 5.1.1 on 2024-09-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_description_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='laboratory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
        ),
    ]
