# Generated by Django 5.1.1 on 2024-10-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_borrow_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowing_config',
            fields=[
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.laboratory')),
                ('allow_walkin', models.BooleanField(default=False)),
                ('allow_prebook', models.BooleanField(default=False)),
                ('prebook_lead_time', models.TimeField(blank=True, null=True)),
                ('allow_shortterm', models.BooleanField(default=True)),
                ('allow_longterm', models.BooleanField(default=True)),
            ],
        ),
    ]
