# Generated by Django 5.1.1 on 2025-03-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_item_inventory_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='warranty_expirations',
            field=models.DateField(blank=True, null=True),
        ),
    ]
