# Generated by Django 5.1.1 on 2024-10-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_borrowing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_config',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.laboratory', unique=True),
        ),
    ]
