# Generated by Django 5.1.1 on 2024-10-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='modules',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
