# Generated by Django 5.1.1 on 2024-09-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_suppliers_laboratory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_types',
            name='laboratory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
        ),
    ]
