# Generated by Django 5.1.1 on 2025-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_description_warranty_expirations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_description',
            old_name='warranty_expirations',
            new_name='warranty_expiration',
        ),
    ]
