# Generated by Django 5.1.1 on 2025-02-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workinprogress_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinprogress',
            old_name='user_id',
            new_name='user',
        ),
    ]
