# Generated by Django 5.1.1 on 2024-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_types_laboratory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_types',
            old_name='laboratory_id',
            new_name='laboratory',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='laboratory_id',
            new_name='laboratory',
        ),
    ]
