# Generated by Django 5.1.1 on 2025-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_warranty_expirations_item_description_warranty_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_description',
            name='expiry_type',
            field=models.CharField(blank=True, choices=[('Date', 'Date'), ('Usage', 'Usage'), ('Maintenance', 'Maintenance'), ('Warranty', 'Warranty'), ('Temperature', 'Temperature')], max_length=45, null=True),
        ),
    ]
