# Generated by Django 5.1.1 on 2024-10-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_borrowing_config_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item_description',
            name='dimension',
        ),
    ]
