# Generated by Django 5.1.1 on 2024-10-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_laboratory_modules_laboratory_modules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LaboratoryModule',
        ),
    ]
