# Generated by Django 5.1.1 on 2025-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_user_id_workinprogress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_inventory',
            name='current_temperature',
        ),
        migrations.RemoveField(
            model_name='item_inventory',
            name='optimal_temperature',
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
