# Generated by Django 5.1.1 on 2024-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_laboratory_id_item_types_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='suppliername',
            field=models.CharField(max_length=45),
        ),
    ]
