# Generated by Django 5.1.1 on 2024-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_item_description_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
    ]
