# Generated by Django 5.1.1 on 2024-10-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_laboratorymodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow_info',
            name='user',
        ),
        migrations.AlterField(
            model_name='borrowing_config',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.laboratory'),
        ),
    ]
