# Generated by Django 5.1.1 on 2024-09-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_suppliers_description_alter_suppliers_suppliername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='suppliername',
            new_name='supplier_name',
        ),
    ]
