# Generated by Django 5.1.1 on 2025-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_inventory_current_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='lead_time_prep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
