# Generated by Django 5.1.1 on 2024-10-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_borrow_info_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_by', to='core.user'),
        ),
    ]
