# Generated by Django 5.1.1 on 2024-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_description_is_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_types',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
    ]
