# Generated by Django 5.1.1 on 2024-10-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_types_is_consumable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='address',
            new_name='contact_person',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='contactPerson',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
