# Generated by Django 5.1.1 on 2024-09-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_suppliername_suppliers_supplier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='contactPerson',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
        ),
    ]
