# Generated by Django 5.1.1 on 2025-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_description_lead_time_prep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_description',
            name='lead_time_prep',
            field=models.IntegerField(default=0),
        ),
    ]
