# Generated by Django 5.1.1 on 2024-10-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_borrow_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='laboratory_roles',
            fields=[
                ('roles_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laboratory_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(blank=True, max_length=45, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory_roles')),
            ],
        ),
        migrations.AlterField(
            model_name='laboratory_users',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.laboratory_roles'),
        ),
        migrations.DeleteModel(
            name='laboratory_role',
        ),
    ]
