# Generated by Django 5.1.1 on 2024-09-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_suppliers_address_suppliers_contactperson_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_expirations',
            fields=[
                ('expired_date', models.DateField(primary_key=True, serialize=False)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_inventory')),
            ],
        ),
    ]
