# Generated by Django 5.1.1 on 2024-10-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_laboratory_roles_laboratory_permissions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laboratory_roles',
            new_name='laboratory_role',
        ),
    ]
