# Generated by Django 5.1.1 on 2024-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_address_suppliers_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_config',
            name='questions_config',
            field=models.JSONField(default=dict),
        ),
    ]
