# Generated by Django 5.1.5 on 2025-02-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_item_description_lead_time_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_reservations',
            name='r_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
