# Generated by Django 5.1.1 on 2024-10-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_laboratory_roles_laboratory_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laboratory_role',
            new_name='laboratory_roles',
        ),
    ]
