# Generated by Django 5.1.1 on 2024-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_borrowing_config_questions_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_config',
            name='questions_config',
            field=models.JSONField(default=list),
        ),
    ]
