# Generated by Django 5.1.1 on 2024-10-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_laboratory_role_laboratory_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory_permissions',
            old_name='role_id',
            new_name='role',
        ),
    ]
