# Generated by Django 5.1.1 on 2024-10-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_borrowing_config_questions_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_config',
            name='prebook_lead_time',
            field=models.IntegerField(default=0),
        ),
    ]
