# Generated by Django 5.1.5 on 2025-02-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
