# Generated by Django 5.1.1 on 2024-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_borrowing_config_prebook_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='questions_responses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
