# Generated by Django 5.1.1 on 2024-10-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_role_id_laboratory_permissions_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('codename', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='laboratory_permissions',
            unique_together={('role', 'laboratory')},
        ),
    ]
