# Generated by Django 5.1.1 on 2024-10-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_permissions_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laboratory_permissions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permissions',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratory_permissions',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='laboratory_permissions',
            unique_together={('role', 'laboratory', 'permissions')},
        ),
    ]
