# Generated by Django 5.1.1 on 2024-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_borrow_info_questions_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_items',
            name='remarks',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='borrowed_items',
            name='returned_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
