# Generated by Django 5.1.1 on 2024-11-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_laboratory_permissions_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item_transactions',
        ),
    ]
