# Generated by Django 5.1.1 on 2024-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_borrowed_items_remarks_borrowed_items_returned_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowed_items',
            name='returned_qty',
            field=models.IntegerField(default=0),
        ),
    ]
