# Generated by Django 5.1.1 on 2024-10-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_borrowed_items_returned_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='reported_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_reported', models.IntegerField()),
                ('report_reason', models.CharField(max_length=255)),
                ('amount_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.borrow_info')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item_description')),
            ],
        ),
    ]
