# Generated by Django 5.1.1 on 2024-11-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_item_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='module',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
    ]
