# Generated by Django 5.1.1 on 2024-11-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_permissions_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_roles',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
            preserve_default=False,
        ),
    ]
