# Generated by Django 5.1.1 on 2024-10-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_reported_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='remarks',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
