# Generated by Django 5.1.1 on 2024-10-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_borrow_info_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_items',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (0, 'Cleared')], default=1),
        ),
    ]
