# Generated by Django 5.1.1 on 2024-10-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_reported_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_items',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
