# Generated by Django 5.1.1 on 2024-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
