# Generated by Django 5.1.1 on 2024-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reported_items_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
