# Generated by Django 5.1.1 on 2024-11-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reported_items',
            name='id',
        ),
        migrations.AddField(
            model_name='reported_items',
            name='reference_id',
            field=models.CharField(default=0, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow_info',
            name='borrow_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item_description',
            name='item_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='reservation_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
