# Generated by Django 5.1.1 on 2024-10-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_handling',
            name='remarks',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
