# Generated by Django 5.1.1 on 2024-11-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_reported_items_id_reported_items_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_expirations',
            name='expired_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item_expirations',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.item_inventory'),
        ),
    ]
