# Generated by Django 5.1.1 on 2024-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_handling_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
