# Generated by Django 5.1.1 on 2024-11-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_item_expirations_expired_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reported_items',
            old_name='reference_id',
            new_name='report_id',
        ),
    ]
