# Generated by Django 5.1.1 on 2024-11-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_reference_id_reported_items_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reported_items',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
            preserve_default=False,
        ),
    ]
