# Generated by Django 5.1.1 on 2024-10-18 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rooms_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='questions_responses',
        ),
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='remarks',
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='num_people',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratory_reservations',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.rooms'),
        ),
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='status',
            field=models.CharField(default='P', max_length=1),
        ),
    ]
