# Generated by Django 5.1.1 on 2024-11-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_reported_items_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported_items',
            name='borrow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.borrow_info'),
        ),
        migrations.AlterField(
            model_name='reported_items',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item_description'),
        ),
    ]
