# Generated by Django 5.1.1 on 2024-10-21 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_laboratory_reservations_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='TimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('reservation_type', models.CharField(choices=[('class', 'Class Time'), ('hourly', 'Hourly')], default='class', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('time_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timeconfiguration')),
            ],
        ),
    ]
