# Generated by Django 5.1.1 on 2024-10-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_roomconfiguration_timeconfiguration_blockedtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedTime',
            new_name='reservation_blocked',
        ),
        migrations.RenameModel(
            old_name='RoomConfiguration',
            new_name='room_configuration',
        ),
        migrations.RenameModel(
            old_name='TimeConfiguration',
            new_name='time_configuration',
        ),
    ]
