# Generated by Django 5.1.1 on 2024-11-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reported_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='laboratory_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
