# Generated by Django 5.1.1 on 2024-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_blockedtime_reservation_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_reservable',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='room_configuration',
        ),
    ]
