# Generated by Django 5.1.1 on 2024-10-22 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rooms_is_reservable_delete_room_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_blocked',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rooms'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='blocked_time',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='reservation_type',
            field=models.CharField(choices=[('class', 'Class Time'), ('hourly', 'Hourly')], default='class', max_length=10),
        ),
        migrations.AddField(
            model_name='rooms',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time_configuration',
            name='blocked_time',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
