# Generated by Django 5.1.1 on 2024-11-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_reported_items_borrow'),
        ('core', '0033_alter_rooms_room_id'),
    ]

    operations = [
    ]
