# Generated by Django 5.1.1 on 2024-10-22 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_reservation_blocked_room_rooms_blocked_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_configuration',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='reservation_type',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='start_time',
        ),
        migrations.CreateModel(
            name='reservation_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('class', 'Class Time'), ('hourly', 'Hourly')], default='class', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
            ],
        ),
        migrations.DeleteModel(
            name='reservation_blocked',
        ),
        migrations.DeleteModel(
            name='time_configuration',
        ),
    ]
