# Generated by Django 5.1.1 on 2024-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_time_configuration_room_remove_rooms_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_config',
            name='tc_description',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
