# Generated by Django 5.1.1 on 2024-11-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_reported_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_users',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
