# Generated by Django 5.1.1 on 2024-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_laboratory_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_users',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
