# Generated by Django 5.1.1 on 2024-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_reservation_config_tc_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_config',
            name='approval_form',
            field=models.FileField(blank=True, null=True, upload_to='approval_forms/'),
        ),
        migrations.AddField(
            model_name='reservation_config',
            name='require_payment',
            field=models.BooleanField(default=False),
        ),
    ]
