# Generated by Django 5.1.1 on 2024-10-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_reservation_config_approval_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation_config',
            name='leadtime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
