# Generated by Django 5.1.1 on 2024-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_laboratory_users_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_reservations',
            name='filled_approval_form',
            field=models.FileField(blank=True, null=True, upload_to='filled_approval_forms/'),
        ),
    ]
