# Generated by Django 5.1.1 on 2024-10-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_reservation_config_leadtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='contact_number',
        ),
    ]
