# Generated by Django 5.1.1 on 2024-11-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_laboratory_reservations_filled_approval_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_config',
            name='tc_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
