# Generated by Django 5.1.1 on 2024-11-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_reservation_config_tc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='suppliers_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
