# Generated by Django 5.1.1 on 2024-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_laboratory_reservations_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_handling',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='item_handling',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
