# Generated by Django 5.1.1 on 2024-11-13 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_suppliers_suppliers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.rooms'),
        ),
    ]
