# Generated by Django 5.1.1 on 2024-11-13 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_laboratory_reservations_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_reservations',
            name='laboratory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.laboratory'),
            preserve_default=False,
        ),
    ]
