# Generated by Django 5.1.1 on 2024-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_laboratory_reservations_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_inventory',
            name='inventory_item_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
