# Generated by Django 5.1.1 on 2024-11-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_item_inventory_inventory_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
