# Generated by Django 5.1.1 on 2024-11-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_suppliers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed_items',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
