# Generated by Django 5.1.1 on 2024-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_borrowed_items_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='is_limited',
            field=models.BooleanField(default=False),
        ),
    ]
