# Generated by Django 5.1.1 on 2024-11-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_item_description_is_limited'),
        ('core', '0046_item_description_qty_limit'),
    ]

    operations = [
    ]
