# Generated by Django 5.1.1 on 2024-11-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20241116_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='is_limited',
        ),
    ]
