# Generated by Django 5.1.1 on 2024-11-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_item_description_count_per_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_description',
            old_name='count_per_inventory',
            new_name='rec_per_inv',
        ),
    ]
