# Generated by Django 5.1.1 on 2024-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20241116_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_description',
            name='count_per_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
