# Generated by Django 5.1.1 on 2024-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_count_per_inventory_item_description_rec_per_inv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
