# Generated by Django 5.1.1 on 2024-11-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_description',
            name='add_cols',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
