# Generated by Django 5.1.1 on 2024-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_item_description_add_cols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='blocked_time',
            field=models.CharField(default='{}', max_length=45),
        ),
    ]
