# Generated by Django 5.1.1 on 2025-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
