# Generated by Django 5.1.5 on 2025-02-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_borrow_info_notification_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.rooms')),
            ],
            options={
                'unique_together': {('room', 'table_number')},
            },
        ),
    ]
