# Generated by Django 5.1.5 on 2025-02-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=45, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='core.rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='tables',
        ),
    ]
