# Generated by Django 5.1.5 on 2025-02-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_laboratory_reservations_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory_reservations',
            name='table',
        ),
    ]
