# Generated by Django 5.1.5 on 2025-02-01 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_laboratory_reservations_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_reservations',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='core.roomtable'),
        ),
    ]
