# Generated by Django 5.1.5 on 2025-02-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_laboratory_reservations_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtable',
            name='blocked_time',
            field=models.CharField(default='{}', max_length=45),
        ),
    ]
