# Generated by Django 5.1.5 on 2025-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_roomtable_blocked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtable',
            name='blocked_time',
            field=models.JSONField(default=dict),
        ),
    ]
