# Generated by Django 5.1.1 on 2025-02-02 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_roomtable_blocked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory_reservations',
            name='filled_approval_form',
            field=models.FileField(blank=True, null=True, upload_to='filled_approval_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reservation_config',
            name='approval_form',
            field=models.FileField(blank=True, null=True, upload_to='approval_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
