# Generated by Django 5.1.5 on 2025-02-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_laboratory_reservations_filled_approval_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_info',
            name='borrow_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
