# Generated by Django 5.1.1 on 2025-02-05 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_laboratory_reservations_filled_approval_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_expirations',
            name='condition_status',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='optimal_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='remaining_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='current_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_inventory',
            name='optimal_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_expirations',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item_expirations',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.item_inventory'),
        ),
    ]
