# Generated by Django 5.1.5 on 2025-02-06 04:22

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_borrow_info_borrow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_info',
            name='b_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
