# Generated by Django 5.1.1 on 2025-02-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_item_expirations_condition_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_expirations',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='item_description',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
