# Generated by Django 5.1.1 on 2025-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_item_expirations_max_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='item_description',
            name='expiry_type',
            field=models.CharField(blank=True, choices=[('Date', 'Date'), ('Uses', 'Uses'), ('Maintenance', 'Maintenance'), ('Temperature', 'Temperature')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='item_expirations',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
