# Generated by Django 5.1.1 on 2025-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_remove_item_description_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_description',
            name='expiry_type',
            field=models.CharField(blank=True, choices=[('Date', 'Date'), ('Usage', 'Usage'), ('Maintenance', 'Maintenance'), ('Temperature', 'Temperature')], max_length=45, null=True),
        ),
    ]
