# Generated by Django 5.1.1 on 2025-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_item_description_expiry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_expirations',
            name='max_uses',
        ),
        migrations.AddField(
            model_name='item_description',
            name='maintenance_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item_description',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
