# Generated by Django 5.1.1 on 2025-02-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_item_expirations_max_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='maintenance_interval',
        ),
        migrations.AddField(
            model_name='item_description',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
