# Generated by Django 5.1.1 on 2025-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_item_description_maintenance_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_description',
            name='next_maintenance_date',
        ),
        migrations.AddField(
            model_name='item_description',
            name='maintenance_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
