# Generated by Django 5.1.1 on 2025-02-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_remove_item_description_next_maintenance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_expirations',
            name='condition_status',
        ),
        migrations.RemoveField(
            model_name='item_expirations',
            name='current_temperature',
        ),
        migrations.RemoveField(
            model_name='item_expirations',
            name='optimal_temperature',
        ),
    ]
