# Generated by Django 5.1.5 on 2025-02-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_borrow_info_b_user_id'),
        ('core', '0071_remove_item_expirations_condition_status_and_more'),
    ]

    operations = [
    ]
